apiVersion: app/v1
kind: Deployment
metadata:
  name: accelerate3-app
  namespace: app-ob

spec:
  stratregy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavaiable: 0
      maxSurge: 25%
    replicas: 1
    selector:
      matchLabels:
        app: accelerate3-app

    template:
      metadata:
        labels:
          app: accelerate3-app
      
      spec:
        containers:
          - name: accelerate3-app
            image: naspuka/movieapp
            imagePullPolicy: Always